apiVersion: v1
kind: Service
metadata:
  name: external-kube-proxy
  namespace: monitoring
  labels:
    k8s-app: kube-proxy
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: external-kube-proxy
    port: 10249
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-kube-proxy
  namespace: monitoring
  labels:
    k8s-app: kube-proxy
subsets:
- addresses:
  - ip: 192.168.2.100
  - ip: 192.168.2.101
  - ip: 192.168.2.102
  ports:
  - name: external-kube-proxy
    port: 10249
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-kube-proxy
  namespace: monitoring
  labels:
    k8s-app: kube-proxy
spec:
  jobLabel: k8s-app
  endpoints:
  - port: external-kube-proxy
    path: /metrics
    interval: 30s
    scheme: http
  selector:
    matchLabels:
      k8s-app: kube-proxy
  namespaceSelector:
    matchNames:
    - monitoring
