apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-frontend-metrics
  namespace: monitoring 
  labels:
    app: loki
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: loki
  endpoints:
    - port: http-metrics
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: host
