apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.22.2
  name: main
  namespace: monitoring
spec:
  image: quay.io/prometheus/alertmanager:v0.22.2
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.22.2
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 4m
      memory: 100Mi
  volumes:
  - name: localtime
    hostPath:
      path: /etc/localtime
  - name: zoneinfo
    hostPath:
      path: /usr/share/zoneinfo
  volumeMounts:
  - name: localtime
    mountPath: /etc/localtime
    readOnly: true
  - name: zoneinfo
    mountPath: /usr/share/zoneinfo
    readOnly: true
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: 0.22.2
