apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.22.2
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
      http_config:
        follow_redirects: true
      smtp_hello: localhost
      smtp_require_tls: true
      pagerduty_url: https://events.pagerduty.com/v2/enqueue
      opsgenie_api_url: https://api.opsgenie.com/
      wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
      victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
    route:
      receiver: webhookcritical
      group_by:
      - namespace
      - alertname
      continue: false
      routes:
      - receiver: Watchdog
        match:
          alertname: Watchdog
        continue: false
      - receiver: webhookwarning
        match:
          severity: warning
        continue: false
      - receiver: webhookemergency
        match:
          severity: emergency
        continue: false
      - receiver: webhookcritical
        match:
          severity: critical
        continue: false
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
    inhibit_rules:
    - source_match:
        severity: emergency
      target_match_re:
        severity: warning|critical
      equal:
      - namespace
      - alertname
    - source_match:
        severity: critical
      target_match_re:
        severity: warning
      equal:
      - namespace
      - alertname
    receivers:
    - name: Watchdog
    - name: webhookwarning
      webhook_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
        url: http://webhook-dingtalk:8060/dingtalk/webhook1/send
        max_alerts: 0
    - name: webhookcritical
      webhook_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
        url: http://webhook-dingtalk:8060/dingtalk/webhook2/send
        max_alerts: 0
    - name: webhookemergency
      webhook_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
        url: http://webhook-dingtalk:8060/dingtalk/webhook3/send
        max_alerts: 0
    templates: []
type: Opaque
